[build]
  command = "bash scripts/netlify-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Comandos de pré-build para configurar o ambiente
[build.processing]
  skip_processing = false

# Script de pré-build para configurar o ambiente
[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
